language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  #- openjdk8
  - openjdk7
notifications:
  irc:
    channels:
      - "chat.freenode.net#aevalo-test"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
    use_notice: false
    skip_join: true
