language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk8
  - openjdk7
notifications:
  irc:
    channels:
      - "ircnet.eversible.com#aevalo"
      #- "chat.freenode.net#some-other-channel"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
